def compilerImageTitle = "dreamkas-rf-compiler"
def libraryImageTitle = "dreamkas-sf-library"
def fiscatImageTitle = "dreamkas-fiscat-f"
def unitsTestImageTitle = "dreamkas-units"

pipeline{
    agent any
    stages{
        stage("Test"){
            steps{
                dir("AutoTests"){
                    git credentialsId: "fisgo-ci-github", url: "https://github.com/dreamkas/FisGoTests.git", branch: "master"
                }
                sh '''
                    cd {env.WORKSPACE}/AutoTests
                    mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/dkf.xml
                '''
            }
        }
    }
    
    post{
        always{
            echo "Cleaning up workspace..." 
            script{
                if("${IS_WORKSPACE_CLEANING_NEEDED}" == "Yes"){
                    echo "Clean up in progress..."
                    cleanWs()
                }
            }
        }
    }
}

void removeUnusedContainersAndDanglingImages() {
    echo "Removing dangling images..." 
    sh "docker container prune --force"
    sh "docker image prune --filter 'dangling=true' --force"
}